Vsensor thermalctld
sonic-net/sonic-platform-daemons pull request #393
Opened 2023-08-10 01:18 UTC by bmridul

Implementation of SensorMonitor daemon which would provide monitoring of voltage and current sensors.
#### Description

Sensormond daemon is introduced. It collects the voltage and current sensor information from the platform and populates in the StateDB. The sensor data is available to view using CLIs. Sensormond raises syslogs when the sensors report measurement outside the thresholds.

#### Motivation and Context

The change is required for the implementation for the sensor monitoring daemon described in the HLD for voltage and current sensors monitoring.

https://github.com/sonic-net/SONiC/pull/1394

#### How Has This Been Tested?

This is tested with unit test (included in PR) and on target with CLIs and instrumentation of faults.

2023-08-14 02:29 UTC, Junchao-Mellanox requested changes

2023-08-14 02:29 UTC, Junchao-Mellanox commented on sonic-sensormond/scripts/sensormond
> +            available_voltage_sensors = set()
Why only handle this for chassis system? For NON chassis system, PSU also can be hot swapable.

2023-08-14 02:29 UTC, Junchao-Mellanox commented on sonic-sensormond/scripts/sensormond
> +    def _log_on_status_changed(self, normal_status, normal_log, abnormal_log):
duplicate code

2023-08-14 02:29 UTC, Junchao-Mellanox commented on sonic-sensormond/scripts/sensormond
> +    def __del__(self):
duplicate code

2023-08-14 02:29 UTC, Junchao-Mellanox commented on sonic-sensormond/scripts/sensormond
> +        if self.is_chassis_system:
duplicate code

2023-08-14 02:35 UTC, Junchao-Mellanox requested changes

2023-08-14 02:35 UTC, Junchao-Mellanox commented on sonic-sensormond/scripts/sensormond
> +            voltage = try_get(voltage_sensor.get_value)
where is get_unit used?

2023-08-22 05:58 UTC, bmridul commented
@Junchao-Mellanox , Pls check this and other PRs related to this with the updates.

2023-09-01 00:17 UTC, abdosi commented
@Junchao-Mellanox can you please review again
We need to close on this soon.

@bmridul please rebase it as it is out of date

2023-09-01 00:31 UTC, Junchao-Mellanox approved these changes

2023-09-01 17:16 UTC, abdosi approved these changes

2023-09-07 22:29 UTC, merged

2023-09-07 22:30 UTC, abdosi commented
@gechiang we would need in msft repo. Since this is enhancement we would need be able to take in 202205 branch.

2023-09-07 22:59 UTC, gechiang commented
@abdosi, same issues where there is no msft repo for this submodule and there is no plan for build team to support this new msft repo.  So unless it is a bug fix, it will likely not be able to be taken in for the 202205 at all...

2023-09-08 00:57 UTC, Junchao-Mellanox commented
Hi @abdosi , the HLD is not approved, it is in a "Requested Change" status. Should we hold on the merge/cherry-pick until  major comments are addressed?

2023-09-21 12:54 UTC, StormLiangMS commented
new feature, no cherry pick

2023-12-21 22:21 UTC, shivuv commented
@gechiang @abdosi : Can you please help to cherry pick this into 202305 and 202311 branches? If this is not possible, please advise @bmridul to open new PRs against 202305 and 202311 branches.

2023-12-21 22:43 UTC, shivuv commented
@gechiang @abdosi : Can you please help to cherry pick this into 202305 branch?