[chassis][pmon][chassid] Enhance the chassid module on-line or off-line log messages with physical slot number
sonic-net/sonic-platform-daemons pull request #530
Opened 2024-08-07 01:54 UTC by mlok-nokia

#### Description
Per MSFT request, we enhance the module on-line and off-line messages with physical slot number

Before enhance:
pmon#chassisd: Module LINE-CARD0 is on-line!
pmon#chassisd: Module LINE-CARD0  went off-line!
pmon#chassisd: Module LINE-CARD0 recovered on-line!
pmon#chassisd: Module FABRIC-CARD6 is on-line!

After Enhance:
pmon#chassisd: Module LINE-CARD0 (Slot 1) is on-line!
pmon#chassisd: Module LINE-CARD0 (Slot 1) went off-line!
pmon#chassisd: Module LINE-CARD0 (Slot 1) recovered on-line!
pmon#chassisd: Module FABRIC-CARD6 (Slot 7) is on-line!

This change is required by 202205 branch also.

#### Motivation and Context
Per MSFT's request -- In order to easily identify a module within a chassis, we need to report the physical slot number whenever we raised “module” related syslogs.

#### How Has This Been Tested?
Tested with Master branch and 202205 branch.

#### Additional Information (Optional)

2024-08-07 01:56 UTC, mlok-nokia commented
@gechiang @judyjoseph This PR enhances the chassis module on-line and off-line message with physical slot info.  Please review it.  Thanks

2024-08-07 02:17 UTC, mlok-nokia commented
@gechiang @judyjoseph  I just found that this PR did not get merge to 202205 branch while other PRs which are associated withhave been merged to 202205.  Please merge this PR first.

2024-08-07 06:17 UTC, gechiang commented
> @gechiang @judyjoseph I just found this PR #480 have not be merged to 202205 branch while other PRs which are associated with PR #480 have been merged to 202205. Please merge this PRs first.

@mlok-nokia the PR you quoted is no longer allowed for public 202205 branch for this submodule as it is a feature enhancement and not a bug fix and 202205 release owner stopped accepting changes.  We do have internal build that takes it in as a patch already so we are good.

2024-08-07 06:26 UTC, gechiang requested changes
Can you also add the same change for the 4 syslog related to Midplane connectivity issues at line 455, 457, 459, and 465.
Also on line 556 for module down long time please also add the slot info as well.
Thanks!

2024-08-07 14:23 UTC, mlok-nokia commented
> Can you also add the same change for the 4 syslog related to Midplane connectivity issues at line 455, 457, 459, and 465. Also on line 556 for module down long time please also add the slot info as well. Thanks!

@gechiang  I just make the change and tested it. Please review it again.

2024-08-07 15:06 UTC, mlok-nokia commented
> > @gechiang @judyjoseph I just found this PR #480 have not be merged to 202205 branch while other PRs which are associated with PR #480 have been merged to 202205. Please merge this PRs first.
> 
> @mlok-nokia the PR you quoted is no longer allowed for public 202205 branch for this submodule as it is a feature enhancement and not a bug fix and 202205 release owner stopped accepting changes. We do have internal build that takes it in as a patch already so we are good.

Ok. Thanks.

2024-08-07 17:00 UTC, mlok-nokia commented
@gechiang  Do we need this PR for 202205 branch?

2024-08-07 17:59 UTC, rlhui commented
can we also have corresponding test for this?

2024-08-07 18:07 UTC, mlok-nokia commented
> can we also have corresponding test for this?

There are already testcases. But not for checking logging message.

2024-08-07 22:42 UTC, gechiang commented
> @gechiang Do we need this PR for 202205 branch?

yes. but we will do it internally as officially public 202205 is closed...  So once we have this merged, we will pick it up in our next internal build.  For community who also needs this for testing on 202205 MSFT repo will also have to manually patch it in their own internal 202205 based builds...

2024-08-07 22:44 UTC, gechiang approved these changes
LGTM.
Thanks!

2024-08-12 08:56 UTC, arlakshm commented
@kenneth-arista for viz..

2024-08-12 10:17 UTC, arlakshm commented
can we add some unit test?

2024-08-12 16:30 UTC, mlok-nokia commented
> can we add some unit test?
There are UTs for this section of code.  But it is just not able check the log texts.  For this module, adding any new code lines requires to at UT for it. Otherwise, it failed to UT verification during image build.

2024-08-14 17:15 UTC, gechiang commented
All comments seem to have been answered already.  Any other comments? @kenneth-arista any comments? 
Thanks!

2024-08-14 17:56 UTC, kenneth-arista approved these changes
Looks fine to me to add slot info to the syslog messages.

2024-08-14 20:48 UTC, gechiang commented
@arlakshm , please help sign off on this PR.
@rlhui , please help merge this PR.
Thanks!

2024-08-15 08:04 UTC, arlakshm approved these changes

2024-08-15 19:39 UTC, judyjoseph commented
@mlok-nokia a general comment -- there are a few more places in the chassisd script where we just have the Module {} alone, should we add Slot {} there too for uniform logs -- not critical but @gechiang f.y.i

2024-08-15 20:53 UTC, merged

2024-08-15 21:28 UTC, mlok-nokia commented
> @mlok-nokia a general comment -- there are a few more places in the chassisd script where we just have the Module {} alone, should we add Slot {} there too for uniform logs -- not critical but @gechiang f.y.i

It seems like there are only two messages which contains Module {}.  I will take a look if it is feasible to add the slot for since one of them complains Module {} with hostname while another is logging for CLI command "config chassis module shutdown <module>"

2024-08-23 21:47 UTC, mssonicbld commented
Cherry-pick PR to 202405: https://github.com/sonic-net/sonic-platform-daemons/pull/534